- name: create org
  scm_org:
    url: "{{scm_url}}"
    user: "admin"
    password: "pppp"
    org: "{{scm_org}}"
    org_long: "{{scm_org_long}}"
    city: "{{scm_city}}"
    tz: "{{scm_tz}}"
    state: "present"
  register: org_out
- debug:
    var: org_out

- name: remove default HQ IRD site
  scm_site:
    url: "{{scm_url}}"
    user: "admin"
    password: "pppp"
    org: "{{scm_org}}"
    city: "{{scm_city}}"
    site: "HQ"
    state: "absent"
