before_script:
 - pip install -U python-openstackclient
 - pip install -U shade
 - curl -O wget https://raw.githubusercontent.com/ansible/ansible/devel/contrib/inventory/openstack.py
launch:
 script:
   - source obs.rc
   - ansible-playbook -i ./openstack.py launch.yml
   - ansible-playbok -i ./opemstack.py build.yml
 tags:
   - openstack
