ansible_ssh_user: ubuntu
github_user: rstarmer
network_names: [broadband, dslvpn, sdslvpn]
network_cidrs: [192.168.10.0/24, 192.168.20.0/24, 192.168.30.0/24]
ucpe_nodes: [LHR,MIL]
server_key: kumulus
scm_org: FIAT
scm_url: https://sdpdemo.riverbed.cc/api/scm.config/1.0/
scm_cities: ["Paris","London","Milan"]
scm_names: ["CDG","LHR","MIL"]
interfaces: [ens3,ens4,ens5]
interfaces_o: [ens6,ens7,ens8]
bridges_in: [br3,br4,br5]
bridges_out: [br3o,br4o,br5o]

