ansible_ssh_user: ubuntu
build_state: present
os_github_user: rstarmer
os_network_names: [mgmt, broadband, adslvpn, sdslvpn, tenmpls, prompls ]
os_network_cidrs: [192.168.5.0/24, 192.168.10.0/24, 192.168.20.0/24, 192.168.30.0/24, 192.168.40.0/24, 192.168.50.0/24]
os_server_key: kumulus
os_ucpe_nodes: ["SFO","BOS"]
os_irg_nodes: ["IRG","PIRG"]
prov_scm_org: LOREAL
prov_scm_org_long: Loreal Inc.
prov_scm_city: Paris
prov_scm_country: FR
prov_scm_tz: Europe/Berlin
prov_scm_url: https://proscm.service.rvbdemo.com/api/scm.config/1.0/
prov_scm_names: ["IRG","PIRG","SFO","BOS"]
ten_scm_org: LOREAL
ten_scm_org_long: Loreal Inc.
ten_scm_city: Paris
ten_scm_country: FR 
ten_scm_tz: Europe/Berlin
ten_scm_url: https://tenscm.service.rvbdemo.com/api/scm.config/1.0/
ten_scm_names: ["IRG","PIRG","SFO","BOS"]
prowans:
  adslvpn:
    internet: false
    wan_long: ADSL VPN network
  broadband:
    internet: true
    wan_long: Broadband network
  sdslvpn:
    internet: false
    wan_long: SDSL Fixed Line network
  pgwirg0:
    internet: false
    wan_long: Provider IRG vgw segment
tenwans:
  irg0:
    internet: false
    wan_long: Provider IRG vgw segment
  irg3:
    internet: false
    wan_long: Provider IRG vgw segment
  irg4:
    internet: false
    wan_long: Provider IRG vgw segment
  irg5:
    internet: false
    wan_long: Provider IRG vgw segment
  tenadslvpn:
    internet: false
    wan_long: Provider IRG vgw segment
  tenbroadband:
    internet: false
    wan_long: Provider IRG vgw segment
  tenvgw0:
    internet: false
    wan_long: Provider IRG vgw segment
  tenvgw1:
    internet: false
    wan_long: Provider IRG vgw segment
  tenvgw2:
    internet: false
    wan_long: Provider IRG vgw segment
nodes:
  IRG:
    city: Boston
    country: US
    tz: America/New_York
    interfaces:
      - ens4
      - ens5
      - ens6
      - ens7
      - ens8
    bridges:
      broadband:
              interface: ens4
              dhcp: false
      adslvpn:
              interface: ens5
              dhcp: false
      sdslvpn:
              interface: ens6
              dhcp: false
      tmpls:
              interface: ens7
              dhcp: false
      pmpls:
              interface: ens8
              dhcp: false
      pvgwirg0:
              interface: false
              dhcp: true
              ip: 172.31.254.0/24
      tvgw0:
              interface: false
              dhcp: true
      tvgw1:
              interface: false
              dhcp: true
      tvgw2:
              interface: false
              dhcp: true
      tvgw0irg1:
              interface: false
              dhcp: true
      tvgw1irg2:
              interface: false
              dhcp: true
      tvgw2irg3:
              interface: false
              dhcp: true
    vgws:
      tenvgw2:
        wan:
          - tenvgw2
          - irg5
          - broadband
      tenvgw1:
        wan:
          - tenvgw1
          - irg4
          - adslvpn
          - sdslvpn
      tenvgw0:
        gan:
          - tenvgw0
          - irg3
          - broadband
          - adslvpn
          - sdslvpn
    pvgws:
      pvgw:
        wan:
          - irg0
        lan:
          - tenvgw0
          - tenvgw1
          - tenvgw2
  PIRG:
    city: Boston
    country: US
    tz: America/New_York
    interfaces: 
      - ens4
      - ens5
      - ens6
    bridges:
      broadband:
              interface: ens4
              dhcp: false
      adslvpn:
              interface: ens5
              dhcp: false
      tmpls:
              interface: ens6
              dhcp: false
      pgwirg0:
              interface: false
              dhcp: true
              ip: 172.31.254.0/24
    pvgws:
      pvgw:
        wan:
          - pgwirg0
          - broadband
          - adslvpn
  SFO:
    city: San Francisco
    country: US
    tz: America/Los_Angeles
    interfaces:
      - ens4
      - ens5
      - ens6
    bridges:
      broadband:
              interface: ens4
              dhcp: false
      adslvpn:
              interface: ens5
              dhcp: false
      tenremote:
              interface: ens6
              dhcp: false
      tenbroadband:
              interface: false
              dhcp: false
      tenadslvpn:
              interface: false
              dhcp: false
      mgmt:
              interface: false
              dhcp: false
    tenvgws:
      tenvgw:
        wan:
          - tenbroadband
          - tenadslvpn
        lan:
          - tenremote
    pvgws:
      pvgw:
        wan:
          - broadband
          - broadband
          - adslvpn
        lan:
          - tenbroadband
          - tenadslvpn
          - mgmt
  BOS:
    city: Boston
    country: US
    tz: America/New_York
    interfaces:
      - ens4
      - ens5
      - ens6
    bridges:
      broadband:
              interface: ens4
              dhcp: false
      adslvpn:
              interface: ens5
              dhcp: false
      tenremote:
              interface: ens6
              dhcp: false
      tenbroadband:
              interface: false
              dhcp: false
      tenadslvpn:
              interface: false
              dhcp: false
      mgmt:
              interface: false
              dhcp: false
    tvgws:
      tenvgw:
        wan:
          - tenbroadband
          - tenadslvpn
        lan:
          - tenremote
    pvgws:
      pvgw:
        wan:
          - broadband
          - broadband
          - adslvpn
        lan:
          - tenbroadband
          - tenadslvpn
          - mgmt
