- name: create provider wans
  scm_wan:
    url: "{{prov_scm_url}}"
    user: "admin"
    password: "pppp"
    org: "{{prov_scm_org}}"
    wan: "{{item.key}}"
    wan_long: "{{item.value.wan_long}}"
    internet: "{{item.value.internet}}"
    state: "present"
  with_dict: "{{prowans}}"

- name: create tenant wans
  scm_wan:
    url: "{{ten_scm_url}}"
    user: "admin"
    password: "pppp"
    org: "{{ten_scm_org}}"
    wan: "{{item.key}}"
    wan_long: "{{item.value.wan_long}}"
    internet: "{{item.value.internet}}"
    state: "present"
  with_dict: "{{tenwans}}"
