#- name: update network config for multiple bridges
#  become: true
#  become_user: root
#  template:
#    src: templates/10.j2
#    dest: /etc/network/interfaces.d/10-kvm-bridge.cfg
#
- set_fact:
     node_name: "{{ansible_nodename|upper}}"
- include_role:
    name: ubuntu_bridges
- name: update config to avoid cloud-config
  become: true
  become_user: root
  template:
    src: templates/99.j2
    dest: /etc/network/interfaces.d/99-disable-newtork-config.cfg
  register: network_interfaces

- name: remove cloud-init network config
  become: true
  become_user: root
  file:
    dest: /etc/network/interfaces.d/50-cloud-init.cfg
    state: absent

#- name: restart machine
#  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
#  async: 1
#  poll: 0
#  become: true
#  become_user: root
#  ignore_errors: true
#  when: network_interfaces|changed
#- name: waiting for server to come back
#  local_action: wait_for host={{ inventory_hostname }} state=started delay=15 timeout=30
#  when: network_interfaces|changed
