---
- hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - include_role:
        name: scm

- hosts: all
  gather_facts: False
  become: true
  become_user: root
  tasks:
    # Install base resources, applications, docker, libvirt, etc.
    - include_role:
        name: base
    # Create ucpe specific networks, SCM VPN endpoint, etc.
    - include_role:
        name: irg
      when: "'irg' in group_names"
    - include_role:
        name: ucpe
      when: "'ucpe' in group_names"
# register provider sites
    - include_role:
        name: scm_site
      vars:
        scm_url: "{{prov_scm_url}}"
        city: "{{item.value.city}}"
        site: "{{item.key}}"
        tz: "{{item.value.tz}}"
        country: "{{item.value.country}}"
      with_dict: "{{nodes[ansible_hostname|upper]}}"
# register tenant sites
    - include_role:
        name: scm_site
      vars:
        scm_url: "{{ten_scm_url}}"
        city: "{{item.value.city}}"
        site: "{{item.key}}"
        tz: "{{item.value.tz}}"
        country: "{{item.value.country}}"
      with_dict: "{{nodes[ansible_hostname|upper]}}"
        
#    - name: register ucpe vGW image path
#      scm_image:
#        url: "{{scm_url}}"
#        user: "admin"
#        password: "pppp"
#        org: "{{scm_org}}"
#        site: "{{ansible_nodename|upper}}"
#        state: "present"
#      register: image_info
#
#    - include_role:
#        name: kvm_vgw
#      vars:
#        instance_name: vgw
#        image_user: admin
#        image_pass: pppp
#        image_url: "{{image_info.image}}"
#        image_type: qcow2

