---
- hosts: localhost
  connection: local
  tasks:

    - name: create networks for broadband, dslvpn, sdslvpn
      os_network:
        state: present
        name: "{{item}}"
        external: false
      with_items:
        - "{{os_network_names}}"

    - name: create subnets for broadband, dslvpn, sdslvpn
      os_subnet:
        state: present
        network_name: "{{item.0}}"
        name: "{{item.0}}"
        cidr: "{{item.1}}"
        dns_nameservers:
           - 8.8.4.4
           - 8.8.8.8
      with_together:
        - "{{os_network_names}}"
        - "{{os_network_cidrs}}"

    - name: create/update router
      os_router:
        state: present
        name: obs-router
        network: public
        interfaces:
          - "{{os_network_names[0]}}"

    - name: create ucpe nodes
      os_server:
        state: present
        name: "{{item}}"
        image: xenial
        key_name: "{{os_server_key}}"
        timeout: 600
        flavor: 10
        auto_ip: no
        userdata: "{{ lookup('file', 'user-data.txt') }}"
        nics:
          - net-name: "{{os_network_names[0]}}"
          - net-name: "{{os_network_names[1]}}"
          - net-name: "{{os_network_names[2]}}"
        meta:
          hostname: "{{item}}"
          group: ucpe
      with_items: "{{os_ucpe_nodes}}"

    - name: associate floating_ip with ucpe nodes
      os_floating_ip:
        server: "{{item}}"
        nat_destination: "{{os_network_names[0]}}"
        network: public
        state: present
        wait: yes
        timeout: 120
      with_items: "{{os_ucpe_nodes}}"

    - name: create irg nodes
      os_server:
        state: present
        name: "{{item}}"
        image: xenial
        key_name: "{{os_server_key}}"
        timeout: 600
        flavor: 10
        auto_ip: no
        userdata: "{{ lookup('file', 'user-data.txt') }}"
        nics:
          - net-name: "{{os_network_names[0]}}"
          - net-name: "{{os_network_names[1]}}"
          - net-name: "{{os_network_names[2]}}"
          - net-name: "{{os_network_names[3]}}"
          - net-name: "{{os_network_names[4]}}"
        meta:
          hostname: "{{item}}"
          group: ucpe
      with_items: "{{os_irg_nodes}}"

    - name: associate floating_ip with irg nodes
      os_floating_ip:
        server: "{{item}}"
        nat_destination: "{{os_network_names[0]}}"
        network: public
        state: present
        wait: yes
        timeout: 120
      with_items: "{{os_irg_nodes}}"

