---
- hosts: localhost
  connection: local
  tasks:

    - name: delete ucpe nodes
      os_server:
        state: absent
        name: "{{item.key}}"
        image: xenial
        key_name: "{{server_key}}"
        timeout: 600
        flavor: 10
        delete_fip: yes
        nics:
          - net-name: "{{network_names[0]}}"
          - net-name: "{{network_names[1]}}"
          - net-name: "{{network_names[2]}}"
        meta:
          hostname: "{{item.key}}"
          group: ucpe
      with_dict: "{{ucpe_nodes}}"

    - name: delete ird nodes
      os_server:
        state: absent
        name: "{{item.key}}"
        image: xenial
        key_name: "{{server_key}}"
        timeout: 600
        flavor: 10
        delete_fip: yes
        nics:
          - net-name: "{{network_names[0]}}"
          - net-name: "{{network_names[1]}}"
          - net-name: "{{network_names[2]}}"
        meta:
          hostname: "{{item.key}}"
          group: ucpe
      with_dict: "{{ird_nodes}}"

    - name: delete router
      os_router:
        state: absent
        name: obs-router
        network: public
        interfaces:
          - "{{network_names[0]}}"
          - "{{network_names[1]}}"
          - "{{network_names[2]}}"
      ignore_errors: true

    - name: remove networks for broadband, dslvpn, sdslvpn
      os_network:
        state: absent
        name: "{{item}}"
        external: false
      with_items:
        - "{{network_names}}"

    - name: remove ucpe nodes and images
      scm_node:
        url: "{{scm_url}}"
        user: "admin"
        password: "pppp"
        org: "{{scm_org}}"
        site: "{{item.key}}"
        state: "absent"
      with_dict: "{{ucpe_nodes}}"
      ignore_errors: true

    - name: remove ird nodes and images
      scm_node:
        url: "{{scm_url}}"
        user: "admin"
        password: "pppp"
        org: "{{scm_org}}"
        site: "{{item.key}}"
        state: "absent"
      with_dict: "{{ird_nodes}}"
      ignore_errors: true

    - name: remove org
      scm_org:
        url: "{{scm_url}}"
        user: "admin"
        password: "pppp"
        org: "{{scm_org}}"
        city: "none"
        state: "absent"
      ignore_errors: true
