---
- hosts: all
  become: true
  become_user: root
#  gather_facts: False
  tasks:
  #- import_role:
  #    name: base
  - debug: msg="{{item.key}} {{item.value.city}} {{item.value.country}} {{item.value.tz}}"
    with_dict: "{{nodes}}"
    when: item.key == "{{ansible_hostname|upper}}"
