- hosts: ucpe
  gather_facts: False
  become: true
  become_user: root
  tasks:
    # Install base resources, applications, docker, libvirt, etc.
    - include_role:
        name: base
    # Create ucpe specific networks, SCM VPN endpoint, etc.
    - include_role:
        name: ucpe
    - name: register ucpe pvGW image path
      scm_image:
        url: "{{prov_scm_url}}"
        user: "admin"
        password: "pppp"
        org: "{{prov_scm_org}}"
        site: "{{ansible_nodename|upper}}"
        state: "present"
      register: prov_image_info
    - name: register ucpe tvGW image path
      scm_image:
        url: "{{ten_scm_url}}"
        user: "admin"
        password: "pppp"
        org: "{{ten_scm_org}}"
        site: "{{ansible_nodename|upper}}"
        state: "present"
      register: ten_image_info
    - include_role:
        name: kvm_bridge
    - include_role:
        name: kvm_vgw
      vars:
        instance_name: vgw
        image_url: "{{image_info.image}}"
        image_type: zip
        image_pass: pppp
        image_user: admin
        


