- name: install needed packages
  apt:
    name: unzip

- name: get vgw image with password
  get_url:
    url: "{{image_url}}"
    dest: "/var/lib/libvirt/images/{{instance_name}}.zip"
    url_password: "{{image_pass}}"
    url_username: "{{image_user}}"
    mode: 644
  register: vgw_image

- name: extract vGW image
  unarchive:
    src: "/var/lib/libvirt/images/{{instance_name}}.zip"
    remote_src: yes
    dest: "/var/lib/libvirt/images/"
    list_files: yes
 
- find:
    paths: /var/lib/libvirt/
    pattern: '*.qcow2'
    recurse: yes
  register: image_name

- debug: var=image_name

- name: ensure we have a metadata directory to build our instance from
  file:
    path: "/root/{{instance_name}}/" 
    state: directory
    mode: 0755

- name: create a user-data file from the user-data.j2 template
  template: 
    src: templates/user-data.j2
    dest: "/root/{{instance_name}}/user-data"

- mac_addr:
  register: mac_1
- mac_addr:
  register: mac_2
- mac_addr:
  register: mac_3

- name: create the {{instance_name}} cloud-init ISO image
  command: cloud-localds /var/lib/libvirt/images/{{instance_name}}-CD.iso /root/{{instance_name}}/user-data
  args:
    creates: /var/lib/libvirt/images/{{instance_name}}-CI.iso
    chdir: /root/{{instance_name}}/

- name: create vgw xml
  template:
    dest: /root/vwg.xml
    src: templates/xml.j2

- name: define vgw instance
  virt:
    name: vgw
    command: define
    xml: "{{ lookup('template', 'xml.j2') }}"

- name: launch vgw instance
  virt:
    name: vgw
    state: running

#- name: launch kvm for "{{instance_name}}"
#  command: |
#    kvm -m 8192 \
#    -smp 4 \
#    -cdrom "/var/lib/libvirt/images/{{instance_name}}-CD.iso" \
#    -device e1000,netdev=br3,mac="{{mac_1.mac}}" -netdev tap,id=br3,script=/etc/qemu-ifup \
#    -device e1000,netdev=br4,mac="{{mac_2.mac}}" -netdev tap,id=br4,script=/etc/qemu-ifup \
#    -device e1000,netdev=br5,mac="{{mac_3.mac}}" -netdev tap,id=br5,script=/etc/qemu-ifup \
#    -drive file={{image_name.files[0].path}},if=virtio,cache=writeback,index=0 \
#    -vnc 0.0.0.0:5900
